name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build . -t cnsmf 

      - name: Push to ECR (CP)
        id: ecr-cp
        uses: jwalton/gh-ecr-push@v1.3.3
        with:
          access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID_DEV }}
          secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY_DEV }}
          region: eu-west-2
          local-image: cnsmf
          image: ${{ secrets.ECR_NAME_DEV }}:${{ github.sha }}, ${{ secrets.ECR_NAME_DEV }}:dev.latest

      - name: Push to ECR (TP)
        id: ecr-tp
        uses: jwalton/gh-ecr-push@v1.3.3
        with:
          access-key-id: ${{ secrets.TP_ECR_AWS_ACCESS_KEY_ID_DEV }}
          secret-access-key: ${{ secrets.TP_ECR_AWS_SECRET_ACCESS_KEY_DEV }}
          region: eu-west-2
          local-image: cnsmf
          image: ${{ secrets.TP_ECR_NAME_DEV }}:${{ github.sha }}, ${{ secrets.TP_ECR_NAME_DEV }}:latest

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    env:
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE_DEV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update image tag
        env:
          ECR_URL: ${{ secrets.ECR_URL_DEV }}
        run: export IMAGE_TAG=${{ github.sha }} && cat conf/kubernetes/development/deployment.tpl | envsubst > conf/kubernetes/development/deployment.yaml
      - name: Authenticate to the cluster
        env:
          KUBE_CERT: ${{ secrets.KUBE_CERT_DEV }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN_DEV }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER_DEV }}
        run: |
          echo "${KUBE_CERT}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER_DEV} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER_DEV}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN_DEV}
          kubectl config set-context ${KUBE_CLUSTER_DEV} --cluster=${KUBE_CLUSTER_DEV} --user=deploy-user --namespace=${KUBE_NAMESPACE_DEV}
          kubectl config use-context ${KUBE_CLUSTER_DEV}
      - name: Apply manifest files
        run: |
          kubectl -n ${KUBE_NAMESPACE_DEV} apply -f conf/kubernetes/development
